### ISSUE TITLE
Add note to include `deployment` as typical trigger when using this action?

### ISSUE THREAD

**Issue by vincerubinetti** [actions/configure-pages#36]
I know technically this would be a change to the [starter workflows repository](https://github.com/actions/starter-workflows/tree/main/pages), but since I think it only applies when you're using this action, I've created the issue here.

One thing I was wondering about is how to make this action run whenever the `baseurl` of the GitHub Pages site changed. As far as I can tell, that would happen when 1) GitHub Pages is first enabled, 2) when the repo name changes, or 3) the custom domain field changes. It doesn't seem like there are any workflow triggers that hook into a repo's settings, but there is the `deployment` trigger, which (as I interpret it, and in my testing) runs after each time the repo's GitHub Pages is deployed (is there any other kind of "deployment"?).

As such, if you're using this action to get the most up to date `baseurl`, I think you need to run it on the `deployment` trigger. Unfortunately this means that if you're making a commit based off of the change -- e.g. updating `baseurl` in `_config.yaml` -- then pages will build once, then run this action, then make the commit which will make pages build again. So you get duplicate builds, but I don't see a way around it unless GitHub adds more triggers.

Anyway, maybe you could add a note about using this trigger to the readme here?

Or maybe there's a better way that I don't know of?

**Comment by vincerubinetti** [comment]
Actually I guess all of the starter workflows include this action, so maybe this issue can be transferred there. Still, a note about this issue in this repo couldn't hurt either.

**Comment by JamesMGreene** [comment]
Perhaps this deserves some clarification.

This is:
> A GitHub Action to ~enable Pages and~...

(see https://github.com/actions/configure-pages/issues/40#issuecomment-1324541447 for ℹ️ on ☝🏻)

> ...extract various metadata about a site. It can also be used to configure various static site generators we support as [starter workflows](https://github.com/actions/starter-workflows/tree/main/pages).

The goal of this Action is _not_ to update your repository contents, though you _could_ use it that way for supported static site generator configuration file modification. 🤔 

This Action's intent is to:
- (a) ~optionally enable Pages for Actions-based deployments, if it is not already enabled~
  - Again, this feature is currently disabled right now
- (b) offer various site metadata to be used within your Actions workflows as needed, especially for deployment purposes
- (c) _temporarily_ modify the configuration files of supported static site generators only for the duration of a workflow run so that configuration is included when building an artifact to be deployed

Your site URLs should not be changing without input from the repository owner, such as when applying a custom domain name or changing the visibility of the Pages site, so I'm not sure how valuable it would be to be able to have a workflow specifically trigger on such modifications. The correct version of the site should arguably already have been deployed at that point, unless it's newly enabled. 🤔 

That said, as far as I know, you are correct that there currently are not applicable event triggers available for those scenarios. 😕
